# SKA-TDNN reproduce recipe configuration.

# Frontend
frontend: melspec_torch
frontend_conf:
    preemp: true
    n_fft: 512
    log: true
    win_length: 400
    hop_length: 160
    n_mels: 80
    normalize: mn

# Encoder
encoder: ska_tdnn
encoder_conf:
  model_scale: 8
  ndim: 512
  ska_dim: 128
  output_size: 1536

# Pooling
pooling: chn_attn_stat

# Projector
projector: ska_tdnn
projector_conf:
  output_size: 192

# Preprocessor
preprocessor: spk
preprocessor_conf:
  target_duration: 3.0  # seconds
  sample_rate: 16000
  num_eval: 5
  noise_apply_prob: 0.5
  noise_info:
  - [0.2, 'dump/raw/musan_speech.scp', [4, 7], [13, 20]]
  - [1.0, 'dump/raw/musan_noise.scp', [1, 1], [0, 15]]
  - [0.2, 'dump/raw/musan_music.scp', [1, 1], [5, 15]]
  rir_apply_prob: 0.5

# Model conf
model_conf:
  extract_feats_in_collect_stats: false

# Loss
loss: aamsoftmax
loss_conf:
  margin: 0.3
  scale: 30

# Training related
max_epoch: 40
num_att_plot: 0
num_workers: 2
cudnn_deterministic: False
cudnn_benchmark: True
drop_last_iter: True
iterator_type: category
valid_iterator_type: sequence
shuffle_within_batch: False
log_interval: 10
batch_size: 12
valid_batch_size: 32
use_amp: True
keep_nbest_models: 5
grad_clip: 9999
best_model_criterion:
- - valid
  - eer
  - min
num_iters_per_epoch: 56

# Optimizer
optim: adam
optim_conf:
  lr: 0.001
  weight_decay: 0.00005
  amsgrad: False

# Scheduler
scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
  first_cycle_steps: 560 # equal to 10 epochs
  cycle_mult: 1.0
  max_lr: 1.0E-4
  min_lr: 5.0E-7
  warmup_steps: 10
  gamma: 0.75